---
  - name: template config/config 
    copy: src=/data/ansible-playbook/config/{{ item }} dest={{ProjectPath}}/config/{{ item }}
    with_items:
      - 17monipdb.dat
      - serverlist.ini 
      - vidalccert.pem
      - vidalcprikey.pem
      # Alarm lib
      - libemailalarm.so
      - libsmsalarm.so
     
...
