---
- hosts: 106.75.133.85
  tasks:
  - name: Update test-gitrpo to pro-gitrpo use rsync
    shell: rsync -ac --delete --exclude-from='./{{sourceRepo}}/rsync.ini' {{sourceRepo}}/ {{destRepo}}/
    args:
      chdir: /data/M4-Product/www
  
  - name: Add  all change to Product git responsitory 
    shell: git add ./*  chdir=/data/M4-Product/www/{{destRepo}}
  
  - name: Check if need to commit 
    shell: git status | grep "nothing to commit" |wc -l chdir=/data/M4-Product/www/{{destRepo}}
    register: needcommit

  - name: Commit  all change to Product git responsitory 
    shell: git commit -a -m '{{destRepo}}' chdir=/data/M4-Product/www/{{destRepo}}
    when: needcommit == "0"

  - name: Push the change to git server
    shell: git push origin  master chdir=/data/M4-Product/www/{{destRepo}}
    when: needcommit == "0"
...